<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<SpaRoot>ChatApp\</SpaRoot>
		<SpaProxyServerUrl>http://localhost:4200</SpaProxyServerUrl>
		<SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>ChatApp</RootNamespace>
		<AssemblyName>ChatApp</AssemblyName>
		<Configurations>Debug;Release;Stage</Configurations>
	</PropertyGroup>

	<PropertyGroup>
		<Authors>Gilson Joanelo</Authors>
		<Company>Gilson Joanelo</Company>
		<Copyright>Gilson Joanelo 2025/$([System.DateTime]::UtcNow.ToString(yyyy))</Copyright>
		<Product>$(AssemblyName)</Product>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<!--<OutputPath>..\..\..\..\Output\Lib\$(AssemblyName)\Debug\</OutputPath>-->
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<!--<OutputPath>..\..\..\..\Output\Lib\$(AssemblyName)\Release\</OutputPath>-->
		<Optimize>True</Optimize>

		<VersionSuffix>$([System.DateTime]::UtcNow.ToString(yyyy)).$([System.DateTime]::UtcNow.ToString(MM)).$([System.DateTime]::UtcNow.ToString(dd)).$([System.DateTime]::UtcNow.ToString(mmff))</VersionSuffix>
		<AssemblyVersion Condition=" '$(VersionSuffix)' == '' ">0.0.0.1</AssemblyVersion>
		<AssemblyVersion Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</AssemblyVersion>
		<Version Condition=" '$(VersionSuffix)' == '' ">0.0.1.0</Version>
		<Version Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</Version>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Stage|AnyCPU'">
		<!--<OutputPath>..\..\..\..\Output\Lib\$(AssemblyName)\Stage\</OutputPath>-->
		<Optimize>True</Optimize>

		<VersionSuffix>$([System.DateTime]::UtcNow.ToString(yyyy)).$([System.DateTime]::UtcNow.ToString(MM)).$([System.DateTime]::UtcNow.ToString(dd)).$([System.DateTime]::UtcNow.ToString(mmff))</VersionSuffix>
		<AssemblyVersion Condition=" '$(VersionSuffix)' == '' ">0.0.0.1</AssemblyVersion>
		<AssemblyVersion Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</AssemblyVersion>
		<Version Condition=" '$(VersionSuffix)' == '' ">0.0.1.0</Version>
		<Version Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</Version>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="obj\**" />
		<EmbeddedResource Remove="obj\**" />
		<None Remove="obj\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.1" />
	</ItemGroup>

	<ItemGroup>
		<!-- Don't publish the SPA source files, but do show them in the project files list -->
		<Content Remove="$(SpaRoot)**" />
		<None Remove="$(SpaRoot)**" />
		<None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
	</ItemGroup>

	<Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
		<!-- Ensure Node.js is installed -->
		<Exec Command="node --version" ContinueOnError="true">
			<Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
		</Exec>
		<Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
		<Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm i -f" />
	</Target>

	<Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
		<!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
		<!--<Exec WorkingDirectory="$(SpaRoot)" Command="npm i -f" />
        <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" Condition="'$(Configuration)' == 'Release'" />-->
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm run production" Condition="'$(Configuration)' == 'Release'" />

		<!-- Include the newly-built files in the publish output -->
		<ItemGroup>
			<!--<DistFiles Include="$(SpaRoot)dist\**; $(SpaRoot)dist-server\**" />
            <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
                <RelativePath>wwwroot\%(RecursiveDir)%(FileName)%(Extension)</RelativePath>
                <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
                <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            </ResolvedFileToPublish>-->
		</ItemGroup>
	</Target>

</Project>
